#!/bin/sh
#
# Set up environment variables for general build tool to operate
# This buildenv is a sample. It describes the minimal environment
# variables required to set up a port environment.
# Alternate environment configurations of the name setenv_<variant>.sh
# are also available for reading.
#
#
# The ZOPEN_TYPE is required. This indicates whether the Open-Source
# package contents are stored in a 'git' format or a 'tarball' format.
# At some point, other formats (perhaps pax) may be supported
# For this example, we are specifying that we will use a zipped tarball format
# for our build.
#
export ZOPEN_TYPE="TARBALL"

#
# Given the ZOPEN_TYPE, build.sh will then need to know where to download from,
# and what other software is required to be able to build this code.
# Since a TARBALL was selected, the environment variables
# ZOPEN_TARBALL_URL and ZOPEN_TARBALL_DEPS are required to be specified.
# The ZOPEN_TARBALL_URL is the fully-qualified location of the tar.gz format of
# tarball, or the tar.xz format of tarball.
# The ZOPEN_TARBALL_DEPS lists each of the ported tools that are required to be
# able to build the code. In the simplest case, this will include:
#  - curl: required to be able to download the tarball
#  - gz or xz: required to be able to unzip the tarball
#  - git: required by build.sh to be able to apply patches
# Many packages will require basic tools like m4, make.
#
export ZOPEN_TARBALL_URL="http://www.greenwoodsoftware.com/less/less-590.tar.gz"
export ZOPEN_TARBALL_DEPS="make curl gzip" 

export LDFLAGS="-Wl,edit=no"
export ZOPEN_EXTRA_CFLAGS="-O2 -q64 -DPATH_MAX=2048"
#export CFLAGS="-O2 -qascii -q64 -std=gnu11 $(CPPFLAGS) -DPATH_MAX=2048 -D_XOPEN_SOURCE_EXTENDED=1"

export ZOPEN_INSTALL_OPTS="install PREFIX=\$ZOPEN_INSTALL_DIR"
