diff --git a/lesstest/Makefile b/lesstest/Makefile
index 8935138..8ac00b6 100644
--- a/lesstest/Makefile
+++ b/lesstest/Makefile
@@ -10,12 +10,12 @@ LESSTEST_SRC = display.c env.c lesstest.c parse.c pipeline.c log.c run.c term.c
 LESSTEST_OBJ = $(patsubst %.c,%.o,$(LESSTEST_SRC))
 
 lesstest: $(LESSTEST_OBJ)
-	$(CC) $(CFLAGS) $(LDFLAGS) -o lesstest $(LESSTEST_OBJ) $(TERMLIB)
+	$(CC) $(CFLAGS) $(LDFLAGS) -o lesstest $(LESSTEST_OBJ) $(TERMLIB) $(LIBS)
 
 LT_SCREEN_SRC = lt_screen.c unicode.c wchar.c
 LT_SCREEN_OBJ = $(patsubst %.c,%.o,$(LT_SCREEN_SRC))
 lt_screen: $(LT_SCREEN_OBJ)
-	$(CC) $(CFLAGS) $(LDFLAGS) -o lt_screen $(LT_SCREEN_OBJ)
+	$(CC) $(CFLAGS) $(LDFLAGS) -o lt_screen $(LT_SCREEN_OBJ) $(LIBS)
 
 HDR = lesstest.h lt_types.h wchar.h
 *.o: $(HDR)
